[workspace]
members = [
    "tgcryptors-core",
    "tgcryptors-python",
]
resolver = "2"

[workspace.package]
version = "1.3.1"
edition = "2021"
license = "MIT"
rust-version = "1.86"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[profile.bench]
inherits = "release"
debug = true
strip = "none"
